### ISSUE TITLE
Running in colab?

### ISSUE THREAD

**Issue by jdeen33** [jmnybl/syntactic-ngram-builder#1]
Hello! This looks like a really cool project and I was wondering if it is possible to run it in colab? The commands for running the code look like they are for command line

**Comment by jmnybl** [comment]
Hi,

I have not been working on this project for years, but with quick testing it seems to work on colab. It's meant to be run on command line, but you can run the same commands on colab as well, however, I'm not sure what happens on colab if you have large input files.

```
!git clone https://github.com/jmnybl/syntactic-ngram-builder.git
%cd syntactic-ngram-builder
!mkdir outputs

!python2 build_ngrams.py sample.conllu --ngrams --out_dir outputs
```
You should have `sample.conllu` file in your working directory. Note also that this is still python2 code.
